# Generated by Django 3.1.7 on 2021-03-28 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='img')),
                ('company', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2021, 3, 28, 7, 15, 44, 210334, tzinfo=utc))),
            ],
        ),
    ]
